//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// APIKeyInfoFull defines model for APIKeyInfoFull.
type APIKeyInfoFull struct {
	// CreatedAt Creation time
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Key ID
	Id *int64 `json:"id,omitempty"`

	// Name Optional label
	Name *string `json:"name,omitempty"`

	// UserId User ID the key belongs to
	UserId *string `json:"user_id,omitempty"`
}

// APIKeyResponse defines model for APIKeyResponse.
type APIKeyResponse struct {
	// KeyId Key ID
	KeyId *int64 `json:"key_id,omitempty"`

	// Secret The raw API key (shown only once)
	Secret *string `json:"secret,omitempty"`
}

// AdminCreateAPIKeyRequest defines model for AdminCreateAPIKeyRequest.
type AdminCreateAPIKeyRequest struct {
	// Name Optional label for the key
	Name *string `json:"name,omitempty"`

	// UserId The user ID to create the API key for
	UserId string `json:"user_id"`
}

// AdminCreateUserRequest defines model for AdminCreateUserRequest.
type AdminCreateUserRequest struct {
	// User Username
	User string `json:"user"`
}

// Broadcast defines model for Broadcast.
type Broadcast struct {
	ClientId  *string    `json:"client_id,omitempty"`
	Content   *string    `json:"content,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Type      *string    `json:"type,omitempty"`
	User      *string    `json:"user,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// InviteResponse defines model for InviteResponse.
type InviteResponse struct {
	// Code Invite code
	Code *string `json:"code,omitempty"`

	// ExpiresAt Expiration time
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token Authentication token (valid for 24 hours)
	Token *string `json:"token,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// InviteCode Invite code (required for registration)
	InviteCode string `json:"invite_code"`

	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content Message content
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	// Id Message ID
	Id *int64 `json:"id,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// SyncMessagesParams defines parameters for SyncMessages.
type SyncMessagesParams struct {
	// Since Return messages with ID greater than this value
	Since *int64 `form:"since,omitempty" json:"since,omitempty"`

	// Last Maximum number of messages to return (used when since=0)
	Last *int64 `form:"last,omitempty" json:"last,omitempty"`
}

// AdminCreateAPIKeyJSONRequestBody defines body for AdminCreateAPIKey for application/json ContentType.
type AdminCreateAPIKeyJSONRequestBody = AdminCreateAPIKeyRequest

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody = AdminCreateUserRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all API keys (admin only)
	// (GET /api/admin/api-keys)
	AdminListAPIKeys(w http.ResponseWriter, r *http.Request)
	// Create a new API key (admin only)
	// (POST /api/admin/api-keys)
	AdminCreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key (admin only)
	// (DELETE /api/admin/api-keys/{keyId})
	AdminRevokeAPIKey(w http.ResponseWriter, r *http.Request, keyId int64)
	// Create a new user (admin only)
	// (POST /api/admin/users)
	AdminCreateUser(w http.ResponseWriter, r *http.Request)
	// Send a message
	// (POST /api/chat/message)
	SendMessage(w http.ResponseWriter, r *http.Request)
	// Stream messages and events via SSE
	// (GET /api/chat/stream)
	StreamMessages(w http.ResponseWriter, r *http.Request)
	// Sync messages
	// (GET /api/chat/sync)
	SyncMessages(w http.ResponseWriter, r *http.Request, params SyncMessagesParams)
	// Register a new user
	// (POST /api/user)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Generate a new invite code
	// (GET /api/user/invite)
	GetInvite(w http.ResponseWriter, r *http.Request)
	// Authenticate and obtain a token
	// (POST /api/user/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) AdminListAPIKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListAPIKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminCreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminCreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminRevokeAPIKey operation middleware
func (siw *ServerInterfaceWrapper) AdminRevokeAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminRevokeAPIKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminCreateUser operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminCreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamMessages operation middleware
func (siw *ServerInterfaceWrapper) StreamMessages(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamMessages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncMessages operation middleware
func (siw *ServerInterfaceWrapper) SyncMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "last" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last", r.URL.Query(), &params.Last, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/admin/api-keys", wrapper.AdminListAPIKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/admin/api-keys", wrapper.AdminCreateAPIKey)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/admin/api-keys/{keyId}", wrapper.AdminRevokeAPIKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/admin/users", wrapper.AdminCreateUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/chat/message", wrapper.SendMessage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/chat/stream", wrapper.StreamMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/chat/sync", wrapper.SyncMessages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user", wrapper.RegisterUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/user/invite", wrapper.GetInvite)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user/login", wrapper.LoginUser)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Frdbtu4En4VHp5zkQB2rDhOChg4F8027XrbxRZxgwW2MAJaGlusKVIlKSfawu++IClFkiUlyqZOGjSA",
	"L2yJHA5nvm9+SH/DvohiwYFrhcffsPJDiIj9+vrj5D2kE74QbxPGzJNYihikpmDf+xKIhuCSaPMrAOVL",
	"GmsqOB7jX8w7KjjSNALcw3BNopgBHuOhNzzpe8d979Unzxvbz1+4hxdCRkYQDoiGfjZLp7GZorSkfIk3",
	"PUyD+lLvIUWTN+U1DkviKNcno0IU5RqWII0sTiKoS/vDfiEMMTIHVtGcLoXsz4VuUixRIC+btLtQINHk",
	"DdIhoBWkaA5M8KVCWtRk1+Vubp6I+RfwtVnJeeUcVCy4grpXVpBefk8zKfAlNHj4UwhIkiv0+uPEbmxP",
	"heKKI8FZigT3Yb+yv+Xqksz9w+FRAIvR8UnHrQYR5RZJkO/6awJK1zfdxZdoIWTuhof71Ww/yX0rkOOC",
	"FZ8bZGE92sHFEr4mVEKAx59v1pvdbg6DqlZjGBnNQLRmKus0F7pvh3fRq1GpUylI4JMmPXxGgevMesWa",
	"DgdNxvYF18B1dfivwJjooSshWfCf9phwM2E07ARrE2GUJlFcXe1B0ck9KIuLQCmyhDZkbRmGUR+6MeNM",
	"SiHrFof8cQl1fE0YDQxAA+CaEqa6LTHha6qhPc74ImignJuF7MteJ6fDdUwlqMYscmbedcojh/fxVNN2",
	"P4gl5a2UiolSV0I2xIGP+Zuybi5mtmz4HvRsR0SNm71Cx1n79tqcqcUKeF2p14kODWj8zAdmFNpzgDLR",
	"dDhCoUik2m/w9X0C/e+OJu365TyqQNuG36wI6bbOOSyp0reETmrhe3knttFe7gBrB2nlOqTud8T9s4JU",
	"r2KZJoBNgQc3bmyxbim+VzXNJqJ8QK97/N9SPJdwp4ptSGvK9bl61fKpU6Kpo9CVVImkOp2aWtstewpE",
	"gjR8M7/m9tfbXPhvf37CPVeZ26Rt3xaLhVrHeGMEU74QdfXPgTAbCZGjEeVLpECuQZpaxcih2pr6nUy4",
	"zp6tQSo33TsYHnjGfiIGTmKKx/jowDs4svjQoVV/QGI6IKY+Md/6K0jt46UrHI19LTcmgQkqZtgHqrSr",
	"6Uw6kpk77KSh522BhcQxy2LQ4IsSvOhTrMc0RHbi/yQs8Bj/d1B0NIOsnRls9TKFW4iUJHXWq1rNaIjE",
	"AhHG8pJOmXkj7/Be6t2mlUvjDYtfcJLoUEj6NwRu0aPdL/pWyDkNAhPiudCIcGQ9um8UOL6nU/6VAhOu",
	"TcRiOTohG1gwBo8/V7nyebaZ9bBKoojINPda2WVoz27C9iV2J7FQbaAstxrYxRVQ+lQE6Xfbe2tLs6lG",
	"Mi0T2NSI8f2Qt9VFNjgjb2PyBGtR+AggOCUBkrlRXuj2Y9PNIRkRxKF0ElBh3KbXlB0G31aQToKNy1YM",
	"NLRw8hzWYlVwMiaSRKBBKqsbNfswWQjn5znYysXbXOqVjHV30p49MCXd5o7tCuQW6km79+DnpcHIG+1e",
	"gdzaZvWFSHjwnAjo6GGs1oV9pqx3/exdSfDCNQA7ToHlY6xHToAdaHhR7i9f0t9L+rs9/dnjiGb2+SHR",
	"g9IZRjP9Sv3pjqjX0KR3op23Gw3aqZd33Mos+DNR77kg3/gREZRjuop0pSWQqPUAYGpfZy7u0P5ruNYD",
	"WAPX/UJyYYLtA6HadqfTM+Qmmn4+U1khwgNkpaoXb9/lbWe9BtOhNSVoOj3bRkDK/Xb/p9wveX+rpN8+",
	"u9KJ5MXKV1SHaPIGLW3klUiHhCMdUoXWhCVgDyrxGH9NQKZFT6Aot4eehSUDWJCEaTz2Oh3i1U4EyTWN",
	"kgjxJJqDrMBKCySd0nuJggBdhcCRVeD/3n6Lfowo/QD1Zo9xglZc9HU4PMvda0whKayfroB6aooVHEq5",
	"f4OSgi750X1zSZBfWOywHN++E3mpw5+sGJhkd7VCIncrGiBauk/9kdCco6ZU+1YxPXCatyaBd6DdfRre",
	"YbW5dYfdbPKbO70lcKPhEx64PJd64F1mqcz7FZBWQMDEkvL28GZvpXcY2yqX+o/c6VRv3JsumMwApBLf",
	"B6UWCfspQlv5byg/Ujwr/dMBbHkr5ppQjoj704MT6+a7MjWRLLt6HQ8GTPiEhULp8fHo1ckx3sw2/wQA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
