//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Broadcast defines model for Broadcast.
type Broadcast struct {
	ClientId  *string    `json:"client_id,omitempty"`
	Content   *string    `json:"content,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Type      *string    `json:"type,omitempty"`
	User      *string    `json:"user,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// InviteResponse defines model for InviteResponse.
type InviteResponse struct {
	// Code Invite code
	Code *string `json:"code,omitempty"`

	// ExpiresAt Expiration time
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token Authentication token (valid for 24 hours)
	Token *string `json:"token,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// InviteCode Invite code (required for registration)
	InviteCode string `json:"invite_code"`

	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content Message content
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	// Id Message ID
	Id *int64 `json:"id,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// SyncMessagesParams defines parameters for SyncMessages.
type SyncMessagesParams struct {
	// Since Return messages with ID greater than this value
	Since *int64 `form:"since,omitempty" json:"since,omitempty"`

	// Last Maximum number of messages to return (used when since=0)
	Last *int64 `form:"last,omitempty" json:"last,omitempty"`
}

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a message
	// (POST /api/chat/message)
	SendMessage(w http.ResponseWriter, r *http.Request)
	// Sync messages
	// (GET /api/chat/sync)
	SyncMessages(w http.ResponseWriter, r *http.Request, params SyncMessagesParams)
	// Register a new user
	// (POST /api/user)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Generate a new invite code
	// (GET /api/user/invite)
	GetInvite(w http.ResponseWriter, r *http.Request)
	// Authenticate and obtain a token
	// (POST /api/user/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncMessages operation middleware
func (siw *ServerInterfaceWrapper) SyncMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "last" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last", r.URL.Query(), &params.Last, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/chat/message", wrapper.SendMessage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/chat/sync", wrapper.SyncMessages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user", wrapper.RegisterUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/user/invite", wrapper.GetInvite)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user/login", wrapper.LoginUser)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fhtb9s2EP4rHLcPCaDEiuOkgIB9aNAu87ABRdpgwIIgYMSzxU4ilePJiVf4vw8kpciypcXbmrZ7AfzB",
	"lMi7h3fPvekDT01RGg2aLE8+cJtmUAj/9wyNkKmw5BYlmhKQFPhXaa5A042SbgEPoihz4AkXt+nR+JhH",
	"nJalW1tCped8FfHUaAJN3e3fQ56biN0bzOVXfac25E/GEZ8ZLATxhCtNp5P2kNIEc0B3ilQBlkRRdrWN",
	"4/HpQXxyEL94F8eJ//3C1wRKQXDgzvYhCQ/WxRVgrZj3bq4s4IZhcpX2bH0UzM3te0jJHX6NaHDb4tA8",
	"boUqvRC5kixFkKBJidzupmKqF4rgAmxptIUe7xrpn0qwKaqSlNE8qU8x/zLayenwUCoEeyNoW9pr9064",
	"BattPuSpoz/jqb7r/mjmSl/AXQV9VC6FtfcG5TbEN82bdWwWUgQauHDj+K6cSwuoxcYdhxmBcFcpBMmT",
	"qyAwajFeD19vyJlkfgW9DeplRZkjTVr7wO1ie4FQM4NsPGGZqdDu9/hawmxycrqb8X8KYTKMr4mjDrXd",
	"vR2vBYHcTc8FzJUlwEE/K0/fmye5zfYaB3g7oJcbmLq/I+//UZSKOpbpI9hb0PLRjQPWXcvvXaT1QdZs",
	"iHbP/xvAGwlPQhximpLD8Kav1pHtVGi2WbiKnC8rVLR868poUHsGAgFdvLnVrV991wj/4ed3PApF10kK",
	"b1tlGVHJV06w0jOzDf8CRO4zIQthpPScWcAFIHv5ZurkKPKmPsdKU/1sAWjD8fhwfBg7+5kStCgVT/jx",
	"YXx47PlBmYc/EqUapZmg0VqkliaQwJnXh8ZU8mTdCzz4DiydGbncYIgoy7xOPKP31ui273D/vkGY8YR/",
	"PWobk1HdlYx6qLjq8oSwAv8gsMBfYRzHz4OgZpqH0M8r6xSuIj75iBBCh9Cj9ExIho1ZnM6j59d5qUVF",
	"mUH1G0in9ORTXHSqyeW/vOE61Bvb+OPJVTfyrq5X1xG3VVEIXNZcZYI1nHZnW6bbpU4duDn0sXyp09q9",
	"1gcKigII0Hqdm/FJFepGi2X3ijI2fcXmvrQho0xoRpmybCHyCnwy5gm/qwCXPOI+xSfcKu0Te2s1CTNR",
	"5cSTeKdEtZX1xIMqqoLpqrgFZGbWIiTDMIDeqyxIdp+BZh7At/H+AL7czQh/Hd713wxXRVDYp7jUDjNt",
	"3haIYvkH0WudKVDBIlD7c8Tw5w6nNl6WOn1kSRsuTXvSXxCapuwy9BzPURE2+76dysHHy4s7lILL9V72",
	"31wKpvU8apCFyU8ytTYzfklsbljDBNNwzzyLO5weBeSDReAcKMwM/Bl7jY05vd/kj3PLHLRD2JDs/9o/",
	"WPvPa0vV3u+QtEOC3I3Ww+nNT97PmNs6Hy4+cZ/b/arQ4we/gdkqTcHaWZX/J1Lb+qe2LymfrX3NASa0",
	"ZOaWhNJMhA87QWw4H9rUCvN6vExGo9ykIs+MpeRk8uL0hK+uV78HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
