//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// APIKeyInfoFull defines model for APIKeyInfoFull.
type APIKeyInfoFull struct {
	// CreatedAt Creation time
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Key ID
	Id *int64 `json:"id,omitempty"`

	// Name Optional label
	Name *string `json:"name,omitempty"`

	// UserId User ID the key belongs to
	UserId *string `json:"user_id,omitempty"`
}

// APIKeyResponse defines model for APIKeyResponse.
type APIKeyResponse struct {
	// KeyId Key ID
	KeyId *int64 `json:"key_id,omitempty"`

	// Secret The raw API key (shown only once)
	Secret *string `json:"secret,omitempty"`
}

// AdminCreateAPIKeyRequest defines model for AdminCreateAPIKeyRequest.
type AdminCreateAPIKeyRequest struct {
	// Name Optional label for the key
	Name *string `json:"name,omitempty"`

	// UserId The user ID to create the API key for
	UserId string `json:"user_id"`
}

// AdminCreateUserRequest defines model for AdminCreateUserRequest.
type AdminCreateUserRequest struct {
	// User Username
	User string `json:"user"`
}

// Broadcast defines model for Broadcast.
type Broadcast struct {
	ClientId  *string    `json:"client_id,omitempty"`
	Content   *string    `json:"content,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Type      *string    `json:"type,omitempty"`
	User      *string    `json:"user,omitempty"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Current password for verification
	CurrentPassword string `json:"current_password"`

	// NewPassword New password to set
	NewPassword string `json:"new_password"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// InviteResponse defines model for InviteResponse.
type InviteResponse struct {
	// Code Invite code
	Code *string `json:"code,omitempty"`

	// ExpiresAt Expiration time
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token Authentication token (valid for 24 hours)
	Token *string `json:"token,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// InviteCode Invite code (required for registration)
	InviteCode string `json:"invite_code"`

	// Password Password
	Password string `json:"password"`

	// User Username
	User string `json:"user"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content Message content
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	// Id Message ID
	Id *int64 `json:"id,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// SyncMessagesParams defines parameters for SyncMessages.
type SyncMessagesParams struct {
	// Since Return messages with ID greater than this value
	Since *int64 `form:"since,omitempty" json:"since,omitempty"`

	// Last Maximum number of messages to return (used when since=0)
	Last *int64 `form:"last,omitempty" json:"last,omitempty"`
}

// AdminCreateAPIKeyJSONRequestBody defines body for AdminCreateAPIKey for application/json ContentType.
type AdminCreateAPIKeyJSONRequestBody = AdminCreateAPIKeyRequest

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody = AdminCreateUserRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all API keys (admin only)
	// (GET /api/admin/api-keys)
	AdminListAPIKeys(w http.ResponseWriter, r *http.Request)
	// Create a new API key (admin only)
	// (POST /api/admin/api-keys)
	AdminCreateAPIKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key (admin only)
	// (DELETE /api/admin/api-keys/{keyId})
	AdminRevokeAPIKey(w http.ResponseWriter, r *http.Request, keyId int64)
	// Create a new user (admin only)
	// (POST /api/admin/users)
	AdminCreateUser(w http.ResponseWriter, r *http.Request)
	// Send a message
	// (POST /api/chat/message)
	SendMessage(w http.ResponseWriter, r *http.Request)
	// Stream messages and events via SSE
	// (GET /api/chat/stream)
	StreamMessages(w http.ResponseWriter, r *http.Request)
	// Sync messages
	// (GET /api/chat/sync)
	SyncMessages(w http.ResponseWriter, r *http.Request, params SyncMessagesParams)
	// Register a new user
	// (POST /api/user)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Generate a new invite code
	// (GET /api/user/invite)
	GetInvite(w http.ResponseWriter, r *http.Request)
	// Authenticate and obtain a token
	// (POST /api/user/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Change user password
	// (POST /api/user/password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) AdminListAPIKeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListAPIKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminCreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminCreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminRevokeAPIKey operation middleware
func (siw *ServerInterfaceWrapper) AdminRevokeAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId int64

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminRevokeAPIKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminCreateUser operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminCreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamMessages operation middleware
func (siw *ServerInterfaceWrapper) StreamMessages(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamMessages(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncMessages operation middleware
func (siw *ServerInterfaceWrapper) SyncMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncMessagesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "last" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "last", r.URL.Query(), &params.Last, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "last"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "last", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncMessages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/admin/api-keys", wrapper.AdminListAPIKeys)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/admin/api-keys", wrapper.AdminCreateAPIKey)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/admin/api-keys/{keyId}", wrapper.AdminRevokeAPIKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/admin/users", wrapper.AdminCreateUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/chat/message", wrapper.SendMessage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/chat/stream", wrapper.StreamMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/chat/sync", wrapper.SyncMessages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user", wrapper.RegisterUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/user/invite", wrapper.GetInvite)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user/login", wrapper.LoginUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/user/password", wrapper.ChangePassword)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FptT9y4Fv4rvr73A0gDM8BApZHuh9LS7my7uwiKVtoKIU9yJnFx7NR2ZshW899XthPyPoSlA0VF4gOT",
	"2MfH5zzPebHzDXsiigUHrhWefMPKCyEi9t/Xp9MPkE75XLxLGDNPYilikJqCfe9JIBr8K6LNLx+UJ2ms",
	"qeB4gt+Yd1RwpGkEeIDhhkQxAzzB+6P9o53R4c7o1afRaGL//sIDPBcyMoKwTzTsZLN0GpspSkvKA7wa",
	"YOo3l/oAKZq+La+xVxJHuT4aF6Io1xCANLI4iaAp7Q/7D2GIkRmwiuY0EHJnJnSbYokCedWm3YUCiaZv",
	"kQ4BXUOKZsAEDxTSoiG7KXd1+0TMvoCnzUrOK2egYsEVNL1yDenV9zSTAk9Ci4c/hYAkWaLXp1O7sS0V",
	"iiVHgrMUCe7BdmV/wfUVmXl7+wc+zMeHRz236keUWyRBvuuvCSjd3HQfX6K5kLkbHu5Xs/0k961AjgtW",
	"fG6QufVoDxdL+JpQCT6efL5d73K9OQyqOo1hZLQD0ZqprNNM6B07vI9erUodS0F8j7Tp4TEKXGfWK9Z0",
	"OGgztie4Bq6rw38BxsQALYVk/n+6Y8LthPF+L1ibCKM0ieLqag+KTu5BWVwESpEAupBVMwyjHvRjxpuQ",
	"8ABOiVJLIf1OJHiJlMYFcTawJU67ESgfYUmyAEnn1LMBvAIXwXwzsMN9HJZrVvodlsUqWiAFuiKbw9K8",
	"7goOZTA2tlVbuw2nJ1IK2bQQ5I9LPOULwqhvKO0D15Qw1c8pU76gGrojsyf8liDlZiH7ctCLJnATUwmq",
	"Ne+emHe9Mu/efbDdtt2PIqC8E3rdQDgtvFbo5rJMx4bvEdC6OdSIZgO8FjDZ9rqcqcU18KZSrxMdGtB4",
	"mQ/MKLTlAGWotT9GoUik2m7x9X1S428usHTrl0eeCrRtwsrKtn7rnEFAlV6TbKiF79Wd2EZbuQOsHaSV",
	"65C63RP3zwpSg4pl2gB2Dty/dWNXAC8yYlXTbCLKBwz6Z8x6MM0k3KliF9LaqqNcvWrB2Ss1N1HoitBE",
	"Up2em+7ELXsMRII0fDO/ZvbXu1z4r39+wgPXy9gyx74tFgu1jvHKCKZ8LprqnwFhNhIiRyPKA6RALkCa",
	"6s7Iodqa+r1MuM6eLUAqN320u787MvYTMXASUzzBB7uj3QOLDx1a9YckpkNiKjrz3841pPZx4EptY1/L",
	"jalvgooZ9pEq7apgk45k5g47aX80qoGFxDHLYtDwixK86OysxzREduL/JMzxBP93WPSAw6wBHNa6v8It",
	"REqSOutVrWY0RGKOCGN5EazMvPFo717qrdPKpfGWxS84SXQoJP0bfLfoweYXfSfkjPq+CfFcaEQ4sh7d",
	"Ngoc3tMp/0qBKdcmYrEcnZANLBiDJ5+rXPl8ubocYJVEEZFp7rWyy9CW3YTt5OxOYqG6QFluzrCLK6D0",
	"sfDT77b3ziZwVY1kWiawahDj+yGv1ne3OCNv/PIEa1H4CCA4Jj6SuVFe6PZj080hGRHEoXR2UmHcatCW",
	"HYbfriGd+iuXrRho6ODkGSzEdcHJmEgSgQaprG7U7MNkIZyfgGErF9e5NCgZ6+6kffnAlLTOHfUKZA31",
	"pN27//PSYDwab16B3Npm9blIuP+cCOjoYazWh32mrHf97F1J8MI1ABtOgeWDv0dOgD1oeFHuL1/S30v6",
	"W5/+7HFEO/u8kOhh6QyjnX6l/nRD1Gtp0nvRbrQZDbqpl3fcyiz4M1HvuSDf+BERlGO6inSlJZCo8wDg",
	"3L7OXNyj/ddwo4ewAK53CsmFCeoHQo3tnp+fIDfR9POZygoR7iMrVb14+y5vO+u1mA4tKEHn5yd1BKTc",
	"6/Z/yr2S92slff3sSieSFysvqQ7R9C0KbOSVSIeEIx1ShRaEJWAPKvEEf01ApkVPoCi3h56FJX2Yk4Rp",
	"PBn1OsRrnAiSGxolEeJJNANZgZUWSDqltxIFPlqGwJFV4P+j7Q79GFH6AepdPsYJWnE12uPwLHevMYWk",
	"sHi6AuqpKVZwKOXeLUoKuuRH9+0lQX5hscFyvH4n8lKHP1kxMM3uaoVE7lbUR7R0n/ojoTlHTan2rWJ6",
	"6DTvTALvQbv7NLzBarN2h91u8ts7vQC40fAJD1yeSz3wPrNU5v0KSCsgYCKgvDu82VvpDca2yqX+I3c6",
	"1Rv3tgsmMwCpxPNAqXnCforQVv4M5UeKZ6UvHcCWt2KmCeWIuI8earAu3923I7v6SdOG4N3+3dQj47xH",
	"As81RJ5V2C+BnqVPAXu0FVGlKA/QnALz1faTRHy0tZSCB8irfbX2vI7ArEvd4dctLVZOhJHpmrpEsuxD",
	"hclwyIRHWCiUnhyOXx0d4tXl6p8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
